name: Provision Azure App Service with Terraform

on:
  push:
    branches:
      - develop
    paths:
      - 'terraform-code/**'
      - '.github/workflows/terraform_script.yml'

jobs:
  terraform:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Change directory to terraform-code
        run: cd terraform-code

      - name: Terraform Init
        run: terraform init
        working-directory: terraform-code

      - name: Terraform Plan
        run: terraform plan
        working-directory: terraform-code

      # - name: Apply Terraform
      #   run: terraform apply -auto-approve
      #   working-directory: terraform-code
      #   env:
      #     ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      #     ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      #     ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      #     ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
